$ cat snap/snapcraft.yaml
name: Blockchain-cli # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: It's a Command line based Blockchain Application which can be used as a frame for building blockchain based Apps.
description: |
 This is a practical Blockchain implementation written in JavaScript. 
 It's a Command line based Blockchain Application which can be used as a frame for building blockchain based Apps.

grade: beta # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
